### PR TITLE
No longer build libuv in .travis.yml

### PR DESCRIPTION
**Pull request by halter73**
The Ubuntu libuv build should now be taken from http://github.com/aspnet/libuv-build

@moozzyk

### CODE REVIEW

**Comment by BrennanConroy** [comment]
:+1: 
You might be able to remove some from the packages list too
https://github.com/aspnet/ServerTests/pull/23/files

**Comment by moozzyk** [comment]
:ship::it:

**Comment by davidfowl** [comment]
But travis is still red

**Comment by cesarbs** [comment]
@davidfowl And complaining about not being able to load libuv (on Linux only):

    Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests.DoesNotHangOnConnectionCloseRequest [FAIL]
    info:       System.AggregateException : One or more errors occurred. (Unable to load DLL 'libuv': The specified module could not be found.
    info:        (Exception from HRESULT: 0x8007007E))
    info:       ---- System.DllNotFoundException : Unable to load DLL 'libuv': The specified module could not be found.
    info:        (Exception from HRESULT: 0x8007007E)
    info:       Stack Trace:
    info:            at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
    info:            at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
    info:            at System.Threading.Tasks.Task.Wait()
    info:            at Microsoft.AspNetCore.Server.Kestrel.KestrelEngine.Start(Int32 count)
    info:            at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
    info:            at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
    info:            at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests.<DoesNotHangOnConnectionCloseRequest>d__4.MoveNext()
    info:         --- End of stack trace from previous location where exception was thrown ---
    info:            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    info:            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    info:         --- End of stack trace from previous location where exception was thrown ---
    info:            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    info:            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    info:         --- End of stack trace from previous location where exception was thrown ---
    info:            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    info:            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    info:         ----- Inner Stack Trace -----
    info:            at Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv.NativeMethods.uv_loop_size()
    info:            at Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv.loop_size()
    info:            at Microsoft.AspNetCore.Server.Kestrel.Networking.UvLoopHandle.Init(Libuv uv)
    info:            at Microsoft.AspNetCore.Server.Kestrel.KestrelThread.ThreadStart(Object parameter)

This is from a [previous run](https://travis-ci.org/aspnet/KestrelHttpServer/jobs/119618193). Most recent one has a compilation error.

**Comment by halter73** [comment]
The first run was from before I changed all the appropriate project.jsons. The most recent build failure is from #717. I'm rerunning now.

**Comment by moozzyk** [comment]
Can it be we still don't have this change? https://github.com/dotnet/corefx/commit/93609c50d3a68b8eed939c1e5252ab7230f2070d#diff-87f02997af704f09ec3f638e6a3b3330

**Comment by halter73** [comment]
Nah. We're all green now. :tada:
